name: Build RustDesk
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        shell: powershell

      - name: Install dependencies
        run: |
          choco install -y pkgconfiglite nasm
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg.exe install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static
          C:\vcpkg\vcpkg.exe integrate install
        shell: powershell

      - name: Install Visual Studio Build Tools with Clang
        run: |
          choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Llvm.Clang"
        shell: powershell

      - name: Build RustDesk
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          $env:PKG_CONFIG_PATH = "C:\vcpkg\installed\x64-windows-static\lib\pkgconfig"
          $env:LIBCLANG_PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin"
          $env:INCLUDE = "C:\vcpkg\installed\x64-windows-static\include"
          $env:OPUS_INCLUDE_DIR = "C:\vcpkg\installed\x64-windows-static\include"
          $env:RUST_BACKTRACE = "1"
          cargo build --release --target x86_64-pc-windows-msvc --verbose
        env:
          RENDEZVOUS_SERVER: rustdesk.getdevnet.com:21116
          RELAY_SERVER: rustdesk.getdevnet.com:21117
          RS_PUB_KEY: hMIWToeeSHrfJLZPWApfwLRm3P15T8hvwrxAskPwjPg=
          API_SERVER: http://rustdesk.getdevnet.com:21114
        shell: powershell

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/x86_64-pc-windows-msvc/release/rustdesk.exe
