name: Flutter Monthly Build

on:
  schedule:
    # schedule build every month at midnight
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  run-flutter-monthly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "monthly"
