name: Flutter Nightly Build

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      web-build: false
      ios-build: flase
      android-build: true
      windows-build: false
      macos-build: false
      linux-build: false
      selfhost: false
      upload-artifact: true
      upload-tag: "nightly"
